- vfs/pom.xml
- vfs/src/main/java/org/jahia/modules/external/vfs/Escaping.java
- vfs/src/main/java/org/jahia/modules/external/vfs/VFSDataSource.java
- vfs/src/test/java/org.jahia.modules.external.vfs/EscapingTest.java
https://jira.jahia.org/browse/QA-9309
> QA-9309: Escape column characters from VFS paths and names

- core/src/main/java/org/jahia/modules/external/admin/mount/AbstractMountPointFactory.java
- core/src/main/java/org/jahia/modules/external/admin/mount/AbstractMountPointFactoryHandler.java
- core/src/main/java/org/jahia/modules/external/admin/mount/config/ConfigMountPointDTO.java
- core/src/main/java/org/jahia/modules/external/admin/mount/config/MountPointConfigFactory.java
- core/src/main/resources/META-INF/definitions.cnd
- core/src/main/resources/META-INF/spring/mod-external-provider.xml
https://jira.jahia.org/browse/BACKLOG-12005
> BACKLOG-12005 : add factory to create mount point from config

- core/src/main/java/org/jahia/modules/external/admin/mount/config/MountPointConfigFactory.java
https://jira.jahia.org/browse/BACKLOG-12007
> Backlog 12007 manage config file deletion

- core/src/main/java/org/jahia/modules/external/admin/mount/config/MountPointConfigFactory.java
https://jira.jahia.org/browse/BACKLOG-12005
> Backlog 12005 check mandatory properties

- vfs/src/main/resources/META-INF/configurations/org.jahia.modules.external.mount-sample.cfg.disabled
https://jira.jahia.org/browse/BACKLOG-12006
> Backlog 12006 example config file

- core/pom.xml
- modules-provider/pom.xml
- pom.xml
- test/pom.xml
- vfs/pom.xml
https://jira.jahia.org/browse/BACKLOG-11952
> BACKLOG-11952: updated dependency

- modules-provider/pom.xml
https://jira.jahia.org/browse/BACKLOG-11952
> BACKLOG-11952 : Update dependency

- core/pom.xml
- modules-provider/pom.xml
- pom.xml
- test/pom.xml
- vfs/pom.xml
https://jira.jahia.org/browse/PROJECT-XXX
> BACKLOG-11952 : Update version

- core/src/main/resources/javascript/locales/fr.json
https://jira.jahia.org/browse/BACKLOG-12213
Add french translation labels
> BACKLOG-12213 Add french translation

- test/pom.xml
https://jira.jahia.org/browse/BACKLOG-11952
> BACKLOG-11952 : Fixed import and dependencies

- core/src/javascript/registrations/externalProvider/registerRoutes.js
- core/src/javascript/registrations/mountpoints/registerRoutes.js
- core/yarn.lock
https://jira.jahia.org/browse/BACKLOG-11710
Add requiredPermission into routes
> BACKLOG-11710: Add requiredPermission into routes

- core/package.json
https://jira.jahia.org/browse/PROJECT-XXX
> BACKLOG-12161: Add descriptor for appshell

- core/src/javascript/registrations/externalProvider/registerRoutes.js
- core/src/javascript/registrations/mountpoints/registerRoutes.js
https://jira.jahia.org/browse/PROJECT-XXX
> BACKLOG-12820: Adapted adminRoute format

- core/src/javascript/registrations/externalProvider/registerRoutes.js
- core/src/javascript/registrations/mountpoints/registerRoutes.js
https://jira.jahia.org/browse/BACKLOG-12935
Simple reordering of the server administration panels
> BACKLOG-12935: reordering of the server settings

- core/src/main/resources/javascript/locales/de.json
- core/src/main/resources/javascript/locales/en.json
- core/src/main/resources/javascript/locales/fr.json
https://jira.jahia.org/browse/BACKLOG-12936
Fixed mount point labels in the administration panel 
> BACKLOG-12936: Fixed labels in server settings

- core/pom.xml
- modules-provider/pom.xml
- test/pom.xml
- vfs/pom.xml
https://jira.jahia.org/browse/BACKLOG-13160
> BACKLOG-13160 : Add spring requirement

- core/pom.xml
- modules-provider/pom.xml
- pom.xml
- test/pom.xml
- vfs/pom.xml
https://jira.jahia.org/browse/QA-13601
> QA-13601: Update dependency to 8.1.0.0

- core/src/main/java/org/jahia/modules/external/ExternalNodeImpl.java
https://jira.jahia.org/browse/QA-13842
> QA-13842: use of the node type from the extension child node

- pom.xml
https://jira.jahia.org/browse/QA-13842
> QA-13842 - Update of the version

- core/pom.xml
- modules-provider/pom.xml
- pom.xml
- test/pom.xml
- vfs/pom.xml
https://jira.jahia.org/browse/QA-13842
> QA-13842 - Update versions of submodules

- core/package.json
- core/pom.xml
- core/src/javascript/index.js
- core/src/javascript/init.js
- core/src/javascript/publicPath.js
- core/webpack.config.js
- core/webpack.shared.js
- core/yarn.lock
https://jira.jahia.org/browse/BACKLOG-15989
> BACKLOG-15989: Update dependencies, use webpack 5

- core/pom.xml
- modules-provider/pom.xml
- vfs/pom.xml
https://jira.jahia.org/browse/BACKLOG-16411
Fixed imports to external-provider-core and vfs to correct version to avoid random wirings
> BACKLOG-16411: specify required imports

- core/src/main/java/org/jahia/modules/external/ExternalSessionImpl.java
https://jira.jahia.org/browse/QA-13929
Refresh extension session
> QA-13929 Refresh extension session

- core/src/main/java/org/jahia/modules/external/ExternalSessionImpl.java
https://jira.jahia.org/browse/QA-13929
Add debug log
> QA-13929 Add debug log

- core/pom.xml
https://jira.jahia.org/browse/QA-13929
Undo signature revert
> QA-13929 Undo signature revert

- core/src/main/java/org/jahia/modules/external/ExternalSessionImpl.java
https://jira.jahia.org/browse/QA-13929
Cherry pick extension session refresh
> Qa 13929 3.x

- test/pom.xml
https://jira.jahia.org/browse/PROJECT-XXX
> QA-13929: update signature

- test/pom.xml
https://jira.jahia.org/browse/QA-13929: update version
Update test-module version corresponding to module-snapshot-version
> QA-13929: update version

- core/src/main/java/org/jahia/modules/external/events/EventServiceImpl.java
https://jira.jahia.org/browse/QA-13986
Logout from session in callback
> QA-13986 Logout from session in callback

- vfs/pom.xml
https://jira.jahia.org/browse/QA-13999 
Use latest SNAPSHOT of the module-test-framework
> QA-13999: Use latest SNAPSHOT of the module-test-framework

- vfs/pom.xml
https://jira.jahia.org/browse/QA-14086
with the missing bridge between log4j and slf4j. This way we do not introduced conflicting version of log4j during the tests between 8.1.0.0 and 8.1.1.0-SNAPSHOT
> QA-14086: Replace module-test-framework 8.1.1.0-SNAPSHOT 

- pom.xml
https://jira.jahia.org/browse/BACKLOG-16717
We need to update the parent Jahia version to have correct log4j classes in Manifest
> BACKLOG-16717: Update parent to 8.1.1.0-SNAPSHOT

- core/package.json
- core/yarn.lock
- vfs/src/main/java/org/jahia/modules/external/vfs/VFSDataSource.java
https://jira.jahia.org/browse/BACKLOG-17240
To validate the fix on VFS just mount a folder with latest iteration of CE 4.1.0-SNAPSHOT
> BACKLOG-17240: Fix vulnerability issues, fix bug in VFS when requesting jcr:content on a folder

- core/pom.xml
- core/src/main/import/repository.xml
- vfs/pom.xml
- vfs/src/main/import/repository.xml
https://jira.jahia.org/browse/TECH-1086
> TECH-1086: Update dependencies

- .github/workflows/on-code-change.yml
- tests/cypress/e2e/vfs.cy.ts
https://jira.jahia.org/browse/QA-14719
> QA-14719: Invert test case until issue is fixed

- tests/cypress/e2e/vfs.cy.ts
- tests/cypress/fixtures/cleanup.groovy
- tests/cypress/fixtures/deleteReference.graphql
- tests/cypress/fixtures/grantAcl.graphql
- tests/cypress/fixtures/revokeAcl.graphql
https://jira.jahia.org/browse/TECH-1115
> TECH-1115: Added tests with acls

- core/src/main/resources/META-INF/patches/sql/postgresql/01-create-jahia-external-provider-schema.resolved.sql
- core/src/main/resources/META-INF/patches/sql/postgresql/02-updateTextToOid.resolved.sql
https://jira.jahia.org/browse/BACKLOG-17331
> BACKLOG-17331: Replace text fields by oid

- core/src/main/resources/META-INF/patches/sql/postgresql/01-create-jahia-external-provider-schema.resolved.sql
- core/src/main/resources/META-INF/patches/sql/postgresql/02-updateTextToOid.resolved.sql
This reverts commit 7517042da57ff7feb944a06d88b0298aae70f4a8.
https://jira.jahia.org/browse/BACKLOG-17331
> Revert "BACKLOG-17331: Replace text fields by oid (#98)"

- pom.xml
It seems that the SNAPSHOT version of the tests have not been pushed since the CI/CD was moved to GitHub Actions
> Also build and publish the test module

- .gitignore
- core/package.json
- core/pom.xml
- core/yarn.lock
https://jira.jahia.org/browse/TECH-1252
Changes only in core module. VFS and modules-provider do not have package.json
> TECH-1252: Add sync-pom configuration

- .github/workflows/on-merge.yml
- .github/workflows/on-release.yml
- core/package.json
- core/pom.xml
- core/webpack.config.js
- core/yarn.lock
- modules-provider/pom.xml
- vfs/pom.xml
https://jira.jahia.org/browse/TECH-1265
Add cyclonedx-maven-plugin and create/upload SBOMs on merge and release
> TECH-1265: Add SBOM creation

- .github/workflows/nightly.yml
> TECH-1415: Fixed nightly workflow

- .github/workflows/nightly.yml
> Split reporting between Jahia release and Jahia snapshot

- core/src/main/java/org/jahia/modules/external/id/ExternalProviderInitializerServiceImpl.java
https://jira.jahia.org/browse/BACKLOG-21608
Deploy Jahia on PostgrSQL 12
Deploy/connect to an LDAP server you should see no errors (users and groups are available)
> BACKLOG-21608: Handle LargeObject in PostgreSQL

- external-provider-ui/README.md
https://jira.jahia.org/browse/TECH-1482
> TECH-1482 - Create README.md

- vfs/src/main/resources/jnt_vfsPointFactoryForm/html/vfsPointFactoryForm.flow/index.jsp
- vfs/src/main/resources/jnt_vfsPointFactoryForm/html/vfsPointFactoryForm.settingsBootstrap3GoogleMaterialStyle.flow/index.jsp
https://jira.jahia.org/browse/TECH-1484
> TECH-1484: Add contextpath

- modules-provider/src/main/java/org/jahia/modules/external/modules/ModulesExportJob.java
https://jira.jahia.org/browse/BACKLOG-20899
> BACKLOG-20899: fix job regsitration

- vfs/src/main/java/org/jahia/modules/external/vfs/VFSDataSource.java
https://jira.jahia.org/browse/QA-15005
> QA-15005: Implement Searchable to allow VanityURL on Files from VFS

- modules-provider/src/main/java/org/jahia/modules/external/modules/ModulesExportJob.java
https://jira.jahia.org/browse/BACKLOG-20899
> BACKLOG-20899: fixed job unregistration

- vfs/src/main/java/org/jahia/modules/external/vfs/VFSDataSource.java
https://jira.jahia.org/browse/BACKLOG-21802
> BACKLOG-21802: Fix supported node types

- modules-provider/src/main/java/org/jahia/modules/external/modules/ModulesExportJob.java
https://jira.jahia.org/browse/BACKLOG-20899
> BACKLOG-20899: avoid npe in shutdown

- core/pom.xml
- vfs/pom.xml
https://jira.jahia.org/browse/TECH-1597
> TECH-1597: Extend graphql import version

- core/src/main/java/org/jahia/modules/external/id/ExternalProviderInitializerServiceImpl.java
https://jira.jahia.org/browse/BACKLOG-22073
Tested on Oracle 19.19, Oracle uses nextval and currval pseudo columns for sequences and not nextval function as in postgresql
> BACKLOG-22073: Fix sequence usage for Oracle with pseudo columns

- core/pom.xml
- core/src/main/java/org/jahia/modules/external/ExternalAccessControlManager.java
- core/src/main/java/org/jahia/modules/external/ExternalPathWrapperImpl.java
- core/src/main/java/org/jahia/modules/external/acl/ExternalDataAce.java
- modules-provider/pom.xml
- modules-provider/src/main/java/org/jahia/modules/external/modules/ModulesDataSource.java
- test/pom.xml
- vfs/pom.xml
https://jira.jahia.org/browse/TECH-1416
Upgrade module to latest jahia-module version and add an explicit dependency to guava (removed from transitive dependency).
> TECH-1416: Upgrade Guava or stop exposing it from core

- core/pom.xml
- modules-provider/pom.xml
- test/pom.xml
https://jira.jahia.org/browse/TECH-1416
Fix compilation issues with missing guava dependencies
> TECH-1416: Fix compilation errors

- .github/workflows/nightly-rl.yml
- .github/workflows/nightly-sn.yml
- .github/workflows/on-code-change.yml
- .github/workflows/on-merge.yml
- core/pom.xml
- external-provider-ui/pom.xml
- modules-provider/pom.xml
- test/pom.xml
- tests/env.run.sh
- tests/provisioning-manifest-build.yml
- tests/provisioning-manifest-snapshot.yml
- vfs/pom.xml
https://jira.jahia.org/browse/TECH-1833
> TECH-1833: Updated versions of modules used for the tests

- .github/workflows/manual-run.yml
- .github/workflows/nightly-rl.yml
- .github/workflows/nightly-sn.yml
- .github/workflows/on-code-change.yml
- .github/workflows/on-merge.yml
- .github/workflows/on-release.yml
- .github/workflows/on-rollback.yml
- .github/workflows/schedule-sonar.yml
https://jira.jahia.org/browse/TECH-1639
> TECH-1639: Updated GitHub Actions versions

- .github/workflows/on-release.yml
> ci: updated to new name of the release workflow

- .github/workflows/manual-run.yml
- .github/workflows/nightly-rl.yml
- .github/workflows/nightly-sn.yml
- .github/workflows/on-code-change.yml
- .github/workflows/on-merge.yml
- .github/workflows/schedule-sonar.yml
- tests/.env.example
> chore: Migrate to gh packages
